# Generated by Django 5.2.5 on 2025-09-11 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderproduct",
            name="color",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="size",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
