# Generated by Django 5.2.5 on 2025-09-12 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderproduct_color_orderproduct_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="color",
        ),
        migrations.RemoveField(
            model_name="orderproduct",
            name="size",
        ),
    ]
