# Generated by Django 5.2.5 on 2025-09-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_remove_orderproduct_variation_orderproduct_variation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderproduct",
            old_name="variation",
            new_name="variations",
        ),
    ]
